name: C/C++ CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
    - name: make check
      run: make test
